@startuml
title Allocation queue - Class Diagram

class Scheduler {
    +constructor(Queue queue, Resources resource)
    -privFunc(Queue q)
    -async privAsyncFunc(Queue queue)
    -Queue _queue
    -Resources _resoures
}

EventEmitter -up-|> Scheduler
@enduml
