@startuml
title Allocation queue - Class Diagram

class Scheduler {
    +constructor(Queue, Resources)
    -test(Queue)
    #async protected(Queue): list of resources
    -Queue _queue: queueue object
    -Resources _resoures
}
@enduml
