@startuml
title Allocation queue - Class Diagram

class Scheduler {
    +constructor(Queue queue, Resource resource)
    -privFunc(Queue q)
    -async privAsyncFunc(Queue queue)
    -Queue _queue
    -Resources _resoures
}

EventEmitter -left-|> Scheduler
@enduml
